version: '3.8'

services:
  default:
    build: .
    init: true
    working_dir: /workspace
    volumes:
    - ./workspace:/workspace
    environment:
      - PYTHONUNBUFFERED=1
    command: tail -f /dev/null
    mem_limit: 2g
    cpus: 2.0
    network_mode: bridge
